version: '3.8'

services:
  user-service:
    image: postgres:15.2
    container_name: user-service
    restart: always
    environment:
      POSTGRES_DB: userdb
      POSTGRES_USER: administration
      POSTGRES_PASSWORD: admin
      POSTGRES_INITDB_ARGS: "--auth=md5"
    ports:
      - "5433:5432"
    volumes:
      - userdb_data:/var/lib/postgresql/data
    networks:
      - backend

  db-test:
    image: postgres:15.2
    container_name: postgres_userdb_test
    restart: always
    environment:
      POSTGRES_DB: userdb_test
      POSTGRES_USER: administration
      POSTGRES_PASSWORD: admin
      POSTGRES_INITDB_ARGS: "--auth=md5"
    ports:
      - "5434:5432"
    volumes:
      - userdb_test_data:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  userdb_data:
  userdb_test_data:

networks:
  backend:
    driver: bridge
